#!/bin/bash
HOME_DIR="/home/aide/aide"

if [ "$1" = "-h" ]; then
	if [ -n "$2" ]; then 
		server=$2
	else
		echo Usage: $0 -h hostname
		exit 1
	fi
else
	echo Usage: $0 -h hostname
	exit 1
fi 

./installClient.expect ${server} #1>/dev/null 2>/dev/null
echo 
echo "Creating home dirs for the client"
mkdir /home/aide/aide/clients/${server} 2>/dev/null
mkdir /home/aide/aide/clients/${server}/logs 2>/dev/null
if [ "$?" = 0 ]; then
	echo -e "[\e[32mOK\e[0m] New dirs has been created."
else
	echo -e "[\e[93mWARRNING\e[0m] This client already has his dirs."
fi

echo "Creating new ${server}.conf"

if [ ! -f ${HOME_DIR}/conf/${server}.conf ]; then
	cp -n ${HOME_DIR}/conf/aide.conf ${HOME_DIR}/conf/${server}.conf 2>/dev/null
	echo -e "[\e[32mOK\e[0m] ${server}.conf has been created."
else
	echo -e "[\e[93mWARRNING\e[0m] ${server}.conf already exists."
fi

echo -e "[\e[32mOK\e[0m] Client ${server} has been successfully installed."
