#!/bin/bash
HOME_DIR="/home/aide/aide"
TEST_MODE=0
usage () {
	echo -e "Usage: $0 -h hostname"
	exit 1
}
while [[ $# -gt 0 ]]; do
i=$1
	case $1 in
		-h)
			SERVER=$2
			shift 2
		;;
		-t)
			TEST_MODE=1
			shift
		;;
		*)
			usage
		;;
	esac
done
if [ -z ${SERVER} ]; then
	usage
fi
echo -ne "Enter password to aide: "
read -s AIDE_PASSWORD; echo
echo -ne "Enter password to root on ${SERVER}: "
read -s SERVER_PASSWORD; echo
if [[ ${TEST_MODE} == 1 ]]; then 
	${HOME_DIR}/scripts/installClient.expect ${SERVER} ${SERVER_PASSWORD} ${AIDE_PASSWORD}
else
	${HOME_DIR}/scripts/installClient.expect ${SERVER} ${SERVER_PASSWORD} ${AIDE_PASSWORD} > /dev/null
fi
if [ "$?" = 0 ]; then
	echo -e "[\e[32mOK\e[0m] Client ${SERVER} has been successfully installed."
else
	echo -e "[\e[31mERROR\e[0m] Expect script failure."
	exit 1
fi
if [[ ${TEST_MODE} == 0 ]]; then
	FLAG=0
	mkdir ${HOME_DIR}/clients/${SERVER} 2>/dev/null && FLAG=$((${FLAG}+1))
	mkdir ${HOME_DIR}/clients/${SERVER}/logs 2>/dev/null && FLAG=$((${FLAG}+1))
	mkdir ${HOME_DIR}/clients/${SERVER}/backup 2>/dev/null && FLAG=$((${FLAG}+1))
	mkdir ${HOME_DIR}/clients/${SERVER}/recovery 2>/dev/null && FLAG=$((${FLAG}+1))
	if [[ ${FLAG} == 4 ]]; then
		echo -e "[\e[32mOK\e[0m] New dirs has been created."
	elif [[ ${FLAG} == 0 ]]; then
		echo -e "[\e[93mWARRNING\e[0m] No new dirs have been created."
	else
		echo -e "[\e[93mWARRNING\e[0m] Only ${FLAG} new dir(s) have been created."
	fi
	if [ ! -f ${HOME_DIR}/conf/${SERVER}.conf ]; then
		cp -n ${HOME_DIR}/conf/aide.conf ${HOME_DIR}/conf/${SERVER}.conf 2>/dev/null
		echo -e "[\e[32mOK\e[0m] ${SERVER}.conf has been created."
	else
		echo -e "[\e[93mWARRNING\e[0m] ${SERVER}.conf already exists."
	fi
fi
